### ISSUE TITLE
the issue of layout

### ISSUE THREAD

**Issue by Charltsing** [aelyo-softworks/Wice#70]

**Comment by Charltsing** [comment]
I don't need your help with layout issues

1.  I want to confirm if the Stack control needs to specify the width or height of its child controls.
2.  Additionally, if possible, please help resolve the issue of ScrollViewer positioning errors after loading text

**Comment by smourier** [comment]
It was a bug in the FastTextBox that was not refreshing itself after being loaded. You can detect that if you slightly resize the window by 1 pixel for example. When doing that in your sample, the textbox immediatly changed its position which is unexpected, overall changes should be smooth.

It should have been corrected in the last commit.

**Comment by Charltsing** [comment]
The issue that FastTextBox that was not refreshing itself after being loaded  may have been resolved in TestWindow.cs, but it still exists in my application. I am not sure where the problem lies and may require more time for analysis.

![Image](https://github.com/user-attachments/assets/715494ca-fc5a-4fd5-b7fe-f5ce0a5d9610)

I will try to reproduce it
